language: node_js
node_js:
  - "0.10"
  - "0.11"

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

env:
  global:
    - secure: "O1YZIFmkKMJ0ZSnwc43PnRN5LhZGFsRnQm99RLYm4vkb5jg49rYCkekpNoullpqc+/Msz88KetbdMZciBiB+9S2gL4jAJLjWPIQrwwkrCPwslE5FVc8jMNiuTV7SMel3M5V3A7Ss1O5Er7NQUlEdChMMT4FACU0NjCFQGG/3xHI="

after_success:
  - "./tools/coverage"
  - "./tools/docs"

deploy:
  provider: npm
  email: github-com@agachi.name
  api_key:
    secure: mbgGlJGgLteOROnKiNcR+DJf5rSx8Ol+2qt5vkxWFsZYdnBi0DW4Z3iScmtWaZVUUDyqf0WT+p/Q9Ef5qM8/Gn7Ryt8bs6U6H+3zKBf7ZUBf+Wg242gFtQQwPrykb5PylN0O55EOaOjDEs9RXEPsjeCa/m64lQOc2hU6P+pI4a8=
  on:
    tags: true
    repo: avaly/backbone-hyper-model
    # Required due to https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
